<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="figures/PDSH-cover-small.png">
*This notebook contains an excerpt from the [Python Data Science Handbook](http://shop.oreilly.com/product/0636920034919.do) by Jake VanderPlas; the content is available [on GitHub](https://github.com/jakevdp/PythonDataScienceHandbook).*

*The text is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work by [buying the book](http://shop.oreilly.com/product/0636920034919.do)!*

<!--NAVIGATION-->
< [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) | [Contents](Index.ipynb) | [Computation on NumPy Arrays: Universal Functions](02.03-Computation-on-arrays-ufuncs.ipynb) >

# 2.2 The Basics of NumPy Arrays / NumPy数组基础

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas ([Chapter 3](03.00-Introduction-to-Pandas.ipynb)) are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.

🐍 Python 中的数据操作几乎等同于 NumPy 数组操作，甚至新出现的 Pandas 工具（第3章将介绍）也是构建在NumPy 数组的基础之上的

Get to know them well!

We'll cover a few categories of basic array manipulations here:

- *Attributes of arrays*: Determining the size, shape, memory consumption, and data types of arrays
- *Indexing of arrays*: Getting and setting the value of individual array elements
- *Slicing of arrays*: Getting and setting smaller subarrays within a larger array
- *Reshaping of arrays*: Changing the shape of a given array
- *Joining and splitting of arrays*: Combining multiple arrays into one, and splitting one array into many

🐍 数组的属性

    确定数组的大小、形状、存储大小、数据类型。

🐍 数组的索引

    获取和设置数组各个元素的值。

🐍 数组的切分

    在大的数组中获取或设置更小的子数组。

🐍 数组的变形

    改变给定数组的形状。

🐍 数组的拼接和分裂

    将多个数组合并为一个，以及将一个数组分裂成多个。

## 2.2.1 NumPy Array Attributes / 数组的属性

First let's discuss some useful array attributes.
We'll start by defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional array.
We'll use NumPy's random number generator, which we will *seed* with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [1]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

#🐍 定义三个随机的数组：一个一维数组、一个二维数组和一个三维数组

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ``ndim`` (the number of dimensions), ``shape`` (the size of each dimension), and ``size`` (the total size of the array):

🐍 每个数组有ndim（数组的维度）、shape（数组每个维度的大小）和 size（数组的总大小）属性

In [2]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [3]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [6]:
a = x3.reshape(3, 5, 2, 2)
a

array([[[[8, 1],
         [5, 9]],

        [[8, 9],
         [4, 3]],

        [[0, 3],
         [5, 0]],

        [[2, 3],
         [8, 1]],

        [[3, 3],
         [3, 7]]],


       [[[0, 1],
         [9, 9]],

        [[0, 4],
         [7, 3]],

        [[2, 7],
         [2, 0]],

        [[0, 4],
         [5, 5]],

        [[6, 8],
         [4, 1]]],


       [[[4, 9],
         [8, 1]],

        [[1, 7],
         [9, 9]],

        [[3, 6],
         [7, 2]],

        [[0, 3],
         [5, 9]],

        [[4, 4],
         [6, 4]]]])

In [7]:
a.ndim

4

Another useful attribute is the ``dtype``, the data type of the array (which we discussed previously in [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb)):

🐍 另外一个有用的属性是 dtype，它是数组的数据类型

In [8]:
print("dtype:", x3.dtype)

dtype: int32


Other attributes include ``itemsize``, which lists the size (in bytes) of each array element, and ``nbytes``, which lists the total size (in bytes) of the array:

🐍 其他的属性包括表示每个数组元素字节大小的itemsize，以及表示数组总字节大小的属性nbytes：

In [8]:
#🐍 可以认为 nbytes 跟 itemsize 和 size 的乘积大小相等

print(f"itemsize:\t{x3.itemsize} bytes")
print(f"nbytes:\t\t{x3.nbytes} bytes")

itemsize:	4 bytes
nbytes:		240 bytes


In general, we expect that ``nbytes`` is equal to ``itemsize`` times ``size``.

## 2.2.2 Array Indexing: Accessing Single Elements / 数组索引：获取单个元素

If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar.
In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

🐍 和 Python列表 一样，在一维数组中，你也可以通过中括号指定索引获取第i 个值（从0 开始计数）：

In [9]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
x1[0]

5

In [11]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [12]:
x1[-1]

9

In [13]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

🐍 在多维数组中，可以用逗号分隔的索引元组获取元素

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
#🐍 0行，0列

x2[0, 0]

3

In [16]:
x2[0][3]

4

In [11]:
a = x2[0]
a

array([3, 5, 2, 4])

In [16]:
# 数组切片高级用法，参考M3

x2[0, :][3]

4

In [19]:
#🐍 2行，0列

x2[2, 0]

1

In [12]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [21]:
#🐍 使用索引方式 修改 元素值

x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

🐍 请注意，和 Python 列表不同，NumPy 数组是固定类型的。这意味着当你试图将一个浮点值插入一个整型数组时，浮点值会被截短成整型。

🐍 并且这种截短是自动完成的，不会给你提示或警告，所以需要特别注意这一点！

In [22]:
x1[0] = 3.14159  # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

## 2.2.3 Array Slicing: Accessing Subarrays / 数组切片：获取子数组

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:

🐍 NumPy 切片语法和 Python 列表的标准切片语法相同

🐍 默认值start=0、stop= 维度的大小（size of dimension）和step=1

``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### 1. One-dimensional subarrays / 一维子数组

In [17]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#🐍 切片是左闭右开区间 [ , )

x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [25]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [26]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [27]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [28]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [29]:
#🐍 step 为负，start 参数 和 stop 参数 默认是被交换的
#🐍 非常方便的逆序数组的方式

x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[5::-2]  # reversed every other from index 5

array([5, 3, 1])

### 2. Multi-dimensional subarrays / 多维子数组

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

In [18]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [33]:
#🐍 切片是左闭右开区间 [ , )

x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [34]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [35]:
#🐍 子数组维度也可以同时被逆序

x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### 3. Accessing array rows and columns / 获取数组的行和列

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

🐍 一种常见的需求是获取数组的单行和单列。你可以将索引与切片组合起来实现这个功能，用一个冒号（:）表示空切片

In [36]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
print(x2[:, 0])  # first column of x2

[12  7  1]


In [39]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

🐍 在获取行时，出于语法的简介考虑，可以省略空的切

In [40]:
#🐍 x2[0] == x2[0, :]

print(x2[0])  # equivalent to x2[0, :]

[12  5  2  4]


### 4. Subarrays as no-copy views / 非副本视图的子数组

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

🐍 关于数组切片有一点很重要也非常有用，那就是数组切片返回的是数组数据的视图，而不是数值数据的副本。这一点也是NumPy 数组切片和Python 列表切片的不同之处：在Python 列表中，切片是值的副本。

In [19]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


Let's extract a $2 \times 2$ subarray from this:

In [42]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [43]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [44]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [46]:
# 创建一个Python列表

x4 = list(range(10))
x4

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [47]:
# Python列表切片是一个副本

a = x4[0:3]
a[0] = 99

print(x4)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[99, 1, 2]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### 5. Creating copies of arrays / 创建数组的副本

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the ``copy()`` method:

In [48]:
#🐍 copy() 方法, 复制数组里的数据或子数组

x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [49]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [50]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## 2.2.4 Reshaping of Arrays / 数组的变形

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [51]:
#🐍 reshape() 函数: 数组的变形

grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

🐍 原始数组的大小必须和变形后数组的大小(size)一致

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

🐍 将一个一维数组转变为二维的行或列的矩阵。你也可以通过 reshape 方法来实现

🐍 更简单地在一个切片操作中利用 newaxis 关键字

In [53]:
x = np.array([1, 2, 3])

# row vector via reshape
a = x.reshape((1, 3))

print(x.shape, a.shape)

(3,) (1, 3)


In [54]:
# row vector via newaxis / newaxis关键字添加维度
b = x[np.newaxis, :]
b.shape

(1, 3)

In [58]:
# column vector via reshape
c = x.reshape((3, 1))
c

array([[1],
       [2],
       [3]])

In [55]:
# column vector via newaxis
d = x[:, None]
d.shape

(3, 1)

In [56]:
d = x[:, np.newaxis]
d.shape

(3, 1)

We will see this type of transformation often throughout the remainder of the book.

## 2.2.5 Array Concatenation and Splitting / 数组拼接和分裂

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### 1. Concatenation of arrays / 数组的拼接

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

🐍 拼接或连接 NumPy 中的两个数组主要由: np.concatenate、np.vstack（垂直栈） 和 np.hstack（水平栈）实现

In [57]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [58]:
# 一次性拼接两个以上数

z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


It can also be used for two-dimensional arrays:

In [59]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [60]:
# concatenate along the first axis / 沿着第一个轴拼接

np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
# concatenate along the second axis (zero-indexed) / 沿着第二个轴拼接（从0开始索引）

np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [62]:
#🐍 np.vstack（垂直栈）

x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [63]:
# horizontally stack the arrays / np.hstack（水平栈）
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similary, ``np.dstack`` will stack arrays along the third axis.

🐍 np.dstack 将沿着第三个维度拼接数组

### 2. Splitting of arrays / 数组的分裂

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

🐍 分裂可以通过np.split、np.hsplit 和np.vsplit 函数来实现

🐍 向以上函数传递一个索引列表作为参数，索引列表记录的是分裂点位置

In [64]:
#🐍  在 x[3] 和 x[5] 处分裂

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

🐍 N 分裂点会得到 N + 1 个子数组。

In [65]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
#🐍 从 grid[2] 行分裂，即 第3行 分裂

upper, lower = np.vsplit(grid, [2])

print(upper)

print("\n")

print(lower)

[[0 1 2 3]
 [4 5 6 7]]


[[ 8  9 10 11]
 [12 13 14 15]]


In [75]:
#🐍 从第 3列 分裂

left, right = np.hsplit(grid, [2])

print(left)
print("\n")
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, ``np.dsplit`` will split arrays along the third axis.

<!--NAVIGATION-->
< [Understanding Data Types in Python](02.01-Understanding-Data-Types.ipynb) | [Contents](Index.ipynb) | [Computation on NumPy Arrays: Universal Functions](02.03-Computation-on-arrays-ufuncs.ipynb) >